version: '3.8'

services:
  db:
    image: postgres
    restart: always
    volumes:
      - "./sql:/docker-entrypoint-initdb.d"
    environment:
      POSTGRES_USER: "docker"
      POSTGRES_PASSWORD: "docker"
      PGDATA: /data/postgres
      POSTGRES_DB: gamebot
    ports:
      - "5432:5432"
  tgbot:
    restart: always
    image: docker.io/library/games-schedule:1.0
    ports:
      - "1234:1234"
    depends_on:
      - db
    environment:
      - BOT_TOKEN=${TOKEN}